### ISSUE TITLE
Bundle not found error

### ISSUE THREAD

**Issue by dmitriz** [alamgird/angular-next-starter-kit#1]
When running `npm run serve`, everything is compiled but in the browser there is this error:

```sh
GET http://localhost:8080/bundle.js 404 (Not Found)
```

Also automatic opening the page in the browser would be sweet (that is commonly done with `serve`), it is very easy with Gulp but I've no clue about Webpack.

**Comment by diit** [comment]
Having same issue, would love to get this working.

**Comment by gpicazo** [comment]
+1

**Comment by alamgird** [comment]
After ```npm run serve```, try navigating to http://localhost:8080/build/index.html

**Comment by diit** [comment]
@alamgird Getting issue with JQuery not being defined.

![image](https://cloud.githubusercontent.com/assets/1082730/12127906/f06a9ad4-b3c7-11e5-80b1-c349783c277e.png)

**Comment by dmitriz** [comment]
Thanks!

Maybe adding something like "open <url>" to make it run automatically?

**Comment by anthony-zingbox** [comment]
Hey guys, I had this same issue when running the module out of the box. Webpack wasn't looking for the build file in the right location. 

Fixed the issue by changing the following in webpack.config.js:
```
output: {
        filename: 'build/bundle.js'
    },
```

To:

```
output: {
        path: __dirname + '/build',
        filename: 'bundle.js'
    },
```

**Comment by alamgird** [comment]
Fixed!
